// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__SitesController from "./admin/sites_controller"
application.register("admin--sites", Admin__SitesController)

import Admin__IssueTypesController from "./admin/issue_types_controller"
application.register("admin--issue_types", Admin__IssueTypesController)

import Admin__UsersController from "./admin/users_controller"
application.register("admin--users", Admin__UsersController)

import Admin__RolesController from "./admin/roles_controller"
application.register("admin--roles", Admin__RolesController)

import Admin__WorkflowsController from "./admin/workflows_controller"
application.register("admin--workflows", Admin__WorkflowsController)

import Admin__SystemSettingsController from "./admin/system_settings_controller"
application.register("admin--system_settings", Admin__SystemSettingsController)

import Admin__CustomFieldsController from "./admin/custom_fields_controller"
application.register("admin--custom_fields", Admin__CustomFieldsController)

import Admin__WorkflowStatesController from "./admin/workflow_states_controller"
application.register("admin--workflow_states", Admin__WorkflowStatesController)

import Admin__StateFlowsController from "./admin/state_flows_controller"
application.register("admin--state_flows", Admin__StateFlowsController)

import Admin__MailTemplatesController from "./admin/mail_templates_controller"
application.register("admin--mail_templates", Admin__MailTemplatesController)

import Admin__ReportsController from "./admin/reports_controller"
application.register("admin--reports", Admin__ReportsController)

import AdminUsers__RegistrationsController from "./admin_users/registrations_controller"
application.register("admin_users--registrations", AdminUsers__RegistrationsController)

import TopController from "./top_controller"
application.register("top", TopController)

import IssuesController from "./issues_controller"
application.register("issues", IssuesController)

import QueriesController from "./queries_controller"
application.register("queries", QueriesController)

import JobHistoriesController from "./job_histories_controller"
application.register("job_histories", JobHistoriesController)

// customizing javascript part.